package scalaprotocompat

import com.google.protobuf.Descriptors.Descriptor
import com.google.protobuf.Descriptors.FieldDescriptor
import com.google.protobuf.Descriptors.FileDescriptor
import com.google.protobuf.compiler.PluginProtos
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse
import scalapb.compiler.DescriptorImplicits
import scalapb.compiler.FunctionalPrinter

import scala.collection.JavaConverters._

class FilePrinter(version: PluginProtos.Version, fd: FileDescriptor, impl: DescriptorImplicits) {
  import impl._

  def result: CodeGeneratorResponse.File = {
    val b = CodeGeneratorResponse.File.newBuilder()
    b.setName(fileName)
    b.setContent(content)
    b.build()
  }

  private def fileName = fd.scalaPackage.fullName.replace(".", "/") + "/ProtoCompatExt.scala"
  private def content = FunctionalPrinter()
    .call(printHeader)
    .print(fd.getMessageTypes().asScala)(printMessage)
    // .print(fd.getMessageTypes().asScala)(printDslMessage)
    .result()

  private def printHeader(p: FunctionalPrinter): FunctionalPrinter = {
    p.add(s"// DO NOT EDIT")
      .add(s"// Generated by: ")
      .add(s"//  protoc ${version.getMajor()}.${version.getMinor()}.${version.getPatch()}")
      .add(s"//  code-gen ${BuildInfo}")
      .newline
      .add(s"package ${fd.scalaPackage.fullName}")
      .newline
  }

  private def printMessage(p: FunctionalPrinter, m: Descriptor): FunctionalPrinter = {
    def printFieldExtensions(f: FieldDescriptor)(p: FunctionalPrinter): FunctionalPrinter = {
      val getter = s"${if (f.isMapField) "Map" else if (f.isRepeated) "List" else ""}"
      val typeName =
        if (f.isMapField) s"java.util.Map[${f.mapType.keyField.javaTypeName}, ${f.mapType.valueField.javaTypeName}]"
        else if (f.isRepeated) s"java.util.List[${f.javaTypeName}]"
        else f.javaTypeName
      p.add(s"inline def ${f.scalaName} = _m.get${f.upperJavaName}${getter}")
        .when(!f.isRepeated && (f.supportsPresence || f.isMessage || f.isInOneof)) {
          _.add(s"inline def optional${f.upperScalaName}: scala.Option[${typeName}] =")
            .indented(_.add(s"if _m.has${f.upperJavaName} then scala.Some(_m.get${f.upperJavaName}) else scala.None"))
        }
        .when(f.isMapField) {
          _.add(s"inline def ${f.scalaName}(_k: ${f.mapType.keyField.javaTypeName}) = _m.get${f.upperJavaName}OrThrow(_k)")
        }
        .when(f.isRepeated && !f.isMapField) {
          _.add(s"inline def ${f.scalaName}(_i: Int) = _m.get${f.upperJavaName}(_i)")
        }
    }
    def printFieldBuilderExtensions(f: FieldDescriptor)(p: FunctionalPrinter): FunctionalPrinter = {
      val indexer = if (f.isRepeated) "(_i: Int)" else ""
      val indexed = if (f.isRepeated) "(_i)" else ""
      p.when(f.isMessage && !f.isMapField) {
        _.add(s"inline def ${f.scalaName}${indexer}: ${f.javaTypeName}.Builder = _b.get${f.upperJavaName}Builder${indexed}")
          .add(s"inline def ${f.scalaName}${indexer}(inline _f: ${f.javaTypeName}.Builder => Unit): Unit = _f(_b.get${f.upperJavaName}Builder${indexed})")
      }.when(!f.isMessage) {
        _.add(s"inline def ${f.scalaName}${indexer}: ${f.javaTypeName} = _b.get${f.upperJavaName}${indexed}")
      }.when(!f.isRepeated) {
        _.add(s"inline def ${f.scalaName}_=(_v: ${f.javaTypeName}): ${m.javaTypeName}.Builder = _b.set${f.upperJavaName}(_v)")
          .when(f.isMessage)(_.add(s"inline def ${f.scalaName}_=(_v: ${f.javaTypeName}.Builder): ${m.javaTypeName}.Builder = _b.set${f.upperJavaName}(_v)"))
          .add(s"inline def ${f.scalaName}_=(_v: scala.Option[${f.javaTypeName}]): ${m.javaTypeName}.Builder = inline _v match")
          .indented(
            _.add(
              s"case scala.Some(_v) => _b.set${f.upperJavaName}(_v)",
              s"case scala.None => _b.clear${f.upperJavaName}()",
              s"case _ => if _v.isDefined then _b.set${f.upperJavaName}(_v.get) else _b.clear${f.upperJavaName}()"
            )
          )
      }
    }
    p.when(m.fields.nonEmpty) {
      _.add(s"extension (inline _m: ${m.javaTypeName})")
        .print(m.fields)((p, f) => p.indented(printFieldExtensions(f)))
        .add(s"end extension")
        .newline
        .add(s"extension (inline _b: ${m.javaTypeName}.Builder)")
        .print(m.fields)((p, f) => p.indented(printFieldBuilderExtensions(f)))
        .add(s"end extension")
        .newline
    }
  }

  private def printDslMessage(p: FunctionalPrinter, m: Descriptor): FunctionalPrinter = {
    def printFieldExtensions(f: FieldDescriptor)(p: FunctionalPrinter): FunctionalPrinter = {
      p.when(!f.isRepeated) {
        _.add(s"inline def ${f.scalaName}_=(_v: ${f.javaTypeName})(using _b: ${m.javaTypeName}.Builder) = _b.set${f.upperJavaName}(_v)")
      }
    }
    p.add(s"inline def ${m.getName.take(1).toLowerCase + m.getName.drop(1)}(inline _f: ${m.javaTypeName}.Builder ?=> Unit): ${m.javaTypeName} =")
      .indented(
        _.add(s"given _b: ${m.javaTypeName}.Builder = ${m.javaTypeName}.newBuilder")
          .add(s"_f")
          .add(s"_b.build()")
      )
      .newline
      .print(m.fields)((p, f) => printFieldExtensions(f)(p))
      .newline

  }

  implicit class FieldImplicitMethods(val fd: FieldDescriptor) {
    def javaTypeName = fd.getJavaType match {
      case FieldDescriptor.JavaType.INT         => "scala.Int"
      case FieldDescriptor.JavaType.LONG        => "scala.Long"
      case FieldDescriptor.JavaType.FLOAT       => "scala.Float"
      case FieldDescriptor.JavaType.DOUBLE      => "scala.Double"
      case FieldDescriptor.JavaType.BOOLEAN     => "scala.Boolean"
      case FieldDescriptor.JavaType.BYTE_STRING => "com.google.protobuf.ByteString"
      case FieldDescriptor.JavaType.STRING      => "scala.Predef.String"
      case FieldDescriptor.JavaType.ENUM        => fd.getEnumType.javaTypeName
      case FieldDescriptor.JavaType.MESSAGE     => fd.getMessageType.javaTypeName
    }
  }
}
