package scalaprotodsl

import com.google.protobuf.Descriptors.Descriptor
import com.google.protobuf.Descriptors.FieldDescriptor
import com.google.protobuf.Descriptors.FileDescriptor
import com.google.protobuf.compiler.PluginProtos
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse
import scalapb.compiler.DescriptorImplicits
import scalapb.compiler.FunctionalPrinter

import scala.jdk.CollectionConverters.*

class FilePrinter(version: PluginProtos.Version, fd: FileDescriptor, impl: DescriptorImplicits):
  import impl.*
  private val ext = Extensions(using impl)
  import ext.*

  def result: CodeGeneratorResponse.File =
    val b = CodeGeneratorResponse.File.newBuilder()
    b.setName(fileName)
    b.setContent(content)
    b.build()

  private def fileName = s"${fd.javaPackage.replace(".", "/")}/${fd.fileDescriptorObject.name}Ext.scala"
  private def content = FunctionalPrinter()
    .call(printHeader)
    .add(s"object ${fd.fileDescriptorObject.name}Ext:")
    .indented(
      _.call(printDslPrelude)
        .print(fd.getMessageTypes().asScala)(printMessage)
        .print(fd.getMessageTypes().asScala)(printDslMessage)
        .print(fd.getMessageTypes().asScala)(printListMessage)
        .print(fd.getMessageTypes().asScala)(printMapMessage)
    )
    .result()

  private def printHeader(p: FunctionalPrinter): FunctionalPrinter =
    p.add(s"// DO NOT EDIT")
      .add(s"// Generated by: ")
      .add(s"//  protoc ${version.getMajor()}.${version.getMinor()}.${version.getPatch()}")
      .add(s"//  code-gen ${BuildInfo}")
      .newline
      .add(s"package ${fd.javaPackage}")
      .newline

  private def printMessage(p: FunctionalPrinter, m: Descriptor): FunctionalPrinter =
    def printFieldExtensions(f: FieldDescriptor)(p: FunctionalPrinter): FunctionalPrinter =
      val getter = s"${if f.isMapField then "Map" else if f.isRepeated then "List" else ""}"
      val typeName =
        if f.isMapField then s"java.util.Map[${f.mapType.keyField.javaTypeName}, ${f.mapType.valueField.javaTypeName}]"
        else if f.isRepeated then s"java.util.List[${f.javaTypeName}]"
        else f.javaTypeName
      p.add(s"inline def ${f.scalaName} = _m.get${f.upperJavaName}${getter}")
        .when(!f.isRepeated && (f.supportsPresence || f.isMessage || f.isInOneof)):
          _.add(s"inline def optional${f.upperScalaName}: scala.Option[${typeName}] =")
            .indented(_.add(s"if _m.has${f.upperJavaName} then scala.Some(_m.get${f.upperJavaName}) else scala.None"))
        .when(f.isMapField):
          _.add(s"inline def ${f.scalaName}(_k: ${f.mapType.keyField.javaTypeName}) = _m.get${f.upperJavaName}OrThrow(_k)")
        .when(f.isRepeated && !f.isMapField):
          _.add(s"inline def ${f.scalaName}(_i: Int) = _m.get${f.upperJavaName}(_i)")
    def printFieldBuilderExtensions(f: FieldDescriptor)(p: FunctionalPrinter): FunctionalPrinter =
      val indexer = if f.isRepeated then "(_i: Int)" else ""
      val indexed = if f.isRepeated then "(_i)" else ""
      p.when(f.isMessage && !f.isMapField):
        _.add(s"inline def ${f.scalaName}${indexer}: ${f.javaTypeName}.Builder = _b.get${f.upperJavaName}Builder${indexed}")
          .add(s"inline def ${f.scalaName}${indexer}(inline _f: ${f.javaTypeName}.Builder => Unit): Unit = _f(_b.get${f.upperJavaName}Builder${indexed})")
      .when(!f.isMessage && !f.isRepeated) {
          _.add(s"inline def ${f.scalaName}: ${f.javaTypeName} = _b.get${f.upperJavaName}")
            .add(s"inline def ${f.scalaName}_=(_v: ${f.javaTypeName}): ${m.javaClassName}.Builder = _b.set${f.upperJavaName}(_v)")
            .add(s"inline def ${f.scalaName}_=(_v: scala.Option[${f.javaTypeName}]): ${m.javaClassName}.Builder = inline _v match")
            .indented(
              _.add(
                s"case scala.Some(_v) => _b.set${f.upperJavaName}(_v)",
                s"case scala.None => _b.clear${f.upperJavaName}()",
                s"case _ => if _v.isDefined then _b.set${f.upperJavaName}(_v.get) else _b.clear${f.upperJavaName}()"
              )
            )
        }
    p.when(m.fields.nonEmpty):
      _.add(s"extension (inline _m: ${m.javaClassName})")
        .print(m.fields)((p, f) => p.indented(printFieldExtensions(f)))
        .add(s"end extension")
        .newline
        .add(s"extension (inline _b: ${m.javaClassName}.Builder)")
        .print(m.fields)((p, f) => p.indented(printFieldBuilderExtensions(f)))
        .add(s"end extension")
        .newline

  private def printDslMessage(p: FunctionalPrinter, m: Descriptor): FunctionalPrinter =
    def printFieldExtensions(f: FieldDescriptor)(p: FunctionalPrinter): FunctionalPrinter =
      p.when(!f.isRepeated):
        _.add(s"inline def ${f.scalaName}_=(_v: ${f.javaTypeName})(using _b: ${m.javaClassName}.Builder) = _b.set${f.upperJavaName}(_v)")
    p.add(s"inline def ${m.getName.take(1).toLowerCase + m.getName.drop(1)}(inline _f: ${m.javaClassName}.Builder ?=> Unit): ${m.javaClassName} =")
      .indented(
        _.add(s"val _b: ${m.javaClassName}.Builder = ${m.javaClassName}.newBuilder")
          .add(s"_f(using _b)")
          .add(s"_b.build()")
      )
      .newline
      .print(m.fields)((p, f) => printFieldExtensions(f)(p))
      .newline

  private def printDslPrelude(p: FunctionalPrinter): FunctionalPrinter =
    // TODO: add extends scala.compiletime.Erased when non-experimental
    p.add(s"sealed trait DslProxy[B]")
      .add(s"type BuilderOf[P <: DslProxy[?]] = P match")
      .indented(_.add(s"case DslProxy[b] => b"))
      .add(s"opaque type DslList[E, P <: DslProxy[?]] = BuilderOf[P]")
      .add(s"opaque type DslMap[K, V, P <: DslProxy[?]] = BuilderOf[P]")
      .newline

  private def printListMessage(p: FunctionalPrinter, m: Descriptor): FunctionalPrinter =
    def printField(f: FieldDescriptor)(p: FunctionalPrinter): FunctionalPrinter =
      val proxy = s"${m.getName}${f.upperScalaName}Proxy"
      def d(tag: String, sig: String) = s"""@scala.annotation.targetName("${f.scalaName}_$tag") inline def $sig"""
      p.add(s"sealed trait $proxy extends DslProxy[${m.javaClassName}.Builder]")
        .add(s"extension (inline _b: ${m.javaClassName}.Builder) inline def ${f.scalaName}: DslList[${f.javaTypeName}, $proxy] = _b")
        .add(s"extension (inline _l: DslList[${f.javaTypeName}, $proxy])")
        .indented(
          _.add(d("size", s"size: Int = _l.get${f.upperJavaName}Count"))
            .add(d("apply", s"apply(_i: Int): ${f.javaTypeName} = _l.get${f.upperJavaName}(_i)"))
            .add(d("add", s"+=(_v: ${f.javaTypeName}): Unit = _l.add${f.upperJavaName}(_v)"))
            .add(
              d("addAll", s"++=(_vs: Iterable[${f.javaBoxedTypeName}]): Unit = _l.addAll${f.upperJavaName}(scala.jdk.javaapi.CollectionConverters.asJava(_vs))")
            )
            .add(d("addAllJava", s"++=(_vs: java.lang.Iterable[${f.javaBoxedTypeName}]): Unit = _l.addAll${f.upperJavaName}(_vs)"))
            .add(d("update", s"update(_i: Int, _v: ${f.javaTypeName}): Unit = _l.set${f.upperJavaName}(_i, _v)"))
            .add(d("clear", s"clear(): Unit = _l.clear${f.upperJavaName}()"))
        )
        .newline
    p.print(m.fields.filter(f => f.isRepeated && !f.isMapField))((p, f) => printField(f)(p))

  private def printMapMessage(p: FunctionalPrinter, m: Descriptor): FunctionalPrinter =
    def printField(f: FieldDescriptor)(p: FunctionalPrinter): FunctionalPrinter =
      val proxy = s"${m.getName}${f.upperScalaName}Proxy"
      val k = f.mapType.keyField.javaTypeName
      val v = f.mapType.valueField.javaTypeName
      val kb = f.mapType.keyField.javaBoxedTypeName
      val vb = f.mapType.valueField.javaBoxedTypeName
      def d(tag: String, sig: String) = s"""@scala.annotation.targetName("${f.scalaName}_$tag") inline def $sig"""
      p.add(s"sealed trait $proxy extends DslProxy[${m.javaClassName}.Builder]")
        .add(s"extension (inline _b: ${m.javaClassName}.Builder) inline def ${f.scalaName}: DslMap[$k, $v, $proxy] = _b")
        .add(s"extension (inline _m: DslMap[$k, $v, $proxy])")
        .indented(
          _.add(d("size", s"size: Int = _m.get${f.upperJavaName}Count"))
            .add(d("apply", s"apply(_k: $k): $v = _m.get${f.upperJavaName}OrThrow(_k)"))
            .add(d("contains", s"contains(_k: $k): Boolean = _m.contains${f.upperJavaName}(_k)"))
            .add(d("update", s"update(_k: $k, _v: $v): Unit = _m.put${f.upperJavaName}(_k, _v)"))
            .add(d("remove", s"-=(_k: $k): Unit = _m.remove${f.upperJavaName}(_k)"))
            .add(d("putAll", s"++=(_kvs: java.util.Map[$kb, $vb]): Unit = _m.putAll${f.upperJavaName}(_kvs)"))
            .add(d("clear", s"clear(): Unit = _m.clear${f.upperJavaName}()"))
        )
        .newline
    p.print(m.fields.filter(_.isMapField))((p, f) => printField(f)(p))

  implicit class FieldImplicitMethods(val fd: FieldDescriptor):
    def javaTypeName = fd.getJavaType match
      case FieldDescriptor.JavaType.INT         => "scala.Int"
      case FieldDescriptor.JavaType.LONG        => "scala.Long"
      case FieldDescriptor.JavaType.FLOAT       => "scala.Float"
      case FieldDescriptor.JavaType.DOUBLE      => "scala.Double"
      case FieldDescriptor.JavaType.BOOLEAN     => "scala.Boolean"
      case FieldDescriptor.JavaType.BYTE_STRING => "com.google.protobuf.ByteString"
      case FieldDescriptor.JavaType.STRING      => "scala.Predef.String"
      case FieldDescriptor.JavaType.ENUM        => fd.getEnumType.javaClassName
      case FieldDescriptor.JavaType.MESSAGE     => fd.getMessageType.javaClassName

    def javaBoxedTypeName = fd.getJavaType match
      case FieldDescriptor.JavaType.INT     => "java.lang.Integer"
      case FieldDescriptor.JavaType.LONG    => "java.lang.Long"
      case FieldDescriptor.JavaType.FLOAT   => "java.lang.Float"
      case FieldDescriptor.JavaType.DOUBLE  => "java.lang.Double"
      case FieldDescriptor.JavaType.BOOLEAN => "java.lang.Boolean"
      case _                                => javaTypeName
